"""added forget password model

Revision ID: 2a648463cce1
Revises: ce5abd1fc480
Create Date: 2025-08-08 17:12:03.498096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a648463cce1'
down_revision = 'ce5abd1fc480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pageViewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_otps', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_otps_email'), ['email'], unique=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_otps_email'))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    op.drop_table('pageViewers')
    # ### end Alembic commands ###
